version: '3'
services:
    first_task:
      build:
        context: ../
        dockerfile: docker/dockerfile
      image: first_task:latest
      ports:
        - 3000:3000
      volumes:
        - ./logs:/logs
      depends_on:
        - mongo
      environment:
        MONGO_URI: mongodb://mongo:27017

    mongo:
      image: mongo
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      restart: always
      
    mongoexpress:
        image: mongo-express
        ports:
            - "8081:8081"
        links:
            - mongo
        environment: 
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017